### ISSUE TITLE
[PR] 별찜을 했을 때 글자도 같이 주황색으로 변하는 버그 수정

### ISSUE THREAD

**Issue by theseeduser** [Starpower/Liberty-skin#1]
PR이 막혀서 여기에 올립니다. layout.html 140줄을 삭제하고 140줄에 `<a href="/member/unstar/{{ document|encode_doc }}" class="btn btn-secondary tools-btn"><span class="fa fa-star" style="color:#ff6200"></span><span>&nbsp;{{ star_count }}</span>` 을 넣으시면 됩니다.

**Comment by theseeduser** [comment]
<a href="/member/unstar/{{ document|encode_doc }}" class="btn btn-secondary tools-btn"><span class="fa fa-star" style="color:#ff6200"></span><span>&nbsp;{{ star_count }}</span>

**Comment by hanoyo** [comment]
PR은 해당 프로젝트가 포크된 상태여야 가능합니다.
